language: python
dist: xenial

cache:
  directories:
  - eggs
  - .npm
  - $ES_HOME

env:
  global:
  - secure: |-
      j9Ako+NzgzqQH8Vj13m/HyAad3nwM9YW/Wdjox7MsSV0xb75G0kuQWf6+hvIi
      Nw10G8z7JQB3Wdh9CWaCf8Lqo2o72NmU1Gm3ZmJWFkHS1PNI7Hlnn80oDddR5
      ruf3fPtHJGAC6cdID4Y+pqqYCnvhAh+BXRLNzve8W8GP9FJJjnK5YDMWv9Bo6
      CxTqiSkQvNogvaNGTHOqEzsdMr8Yan/9Ev4bte+jWmkprBUFVpVbcgJPOM5Vr
      XTF2Aum8lVBYJeG6PtK+F8IpcobpLfnPT38EY5P7nICOoWqdgwGttNPcM7nK+
      +bgpfoonZ7BUUHRf5Dudm5jc3mZGSM0iUAq1jbUjnqHClQUXD+mdcITRE838t
      iIUj+ydOEBVaUNBo76uYO7m79cqJeRpESX9FsikvTBfqE3/kt+CJyxOHewDiS
      Wm594M0LAuLSMcaq9Fl9qQM5LkMYIHe+c9uMTxSCYRkE4EcY8qjyynUXmrJdn
      jPbqH0vvCY6JosvSjFbm8k8Csh3QLhcUE2JuNypPRj/Hzo7F8I1FF5zZLMaWl
      Dxa10WUqDgU8oP2POzWiQGuakECkGK8Om8QjVhvBdi6vVwgZXG5vF3CunVzBR
      Q6baeRBgyeLqOsnqiC9japGKOhYOz1Tta4P679VBurzXaUsmboumARSEGDhpN
      fXLT/z+xeiLw=
  - secure: |-
      N/IgA/htX86U+Tk0+RI15bWKCAEvg2/UuEjWzINRwlrTkPiwqOQdoJ8/DWdDW
      W2qU5a4zrBbS5ZlhHxGcLObsS6grsoscPh8b+sfSTD53YFlDMWfmmDABUVwEl
      gwm4OETRBg2yBkdMi6rusQIuBy/iU1K6B3jv7kC4nYor0ps1r2/QO8VgrTgWt
      J62eRf7kp/EY2k8KBidJtj+ljinHQdBtgzu78QyNBUueLwzme6zZiH9EGMRj5
      Q+sD/Wn+oM09vjsZZjDAWPNVNo+Lvs1M7DsVWfZrVR7+oLnCTGetYpp/2EC5b
      XEd6CnHO7NlHecbuqvr/GyN+55GOSPJxLnRKURGhZwpRQwGr4Apy6URSE7SDI
      kZ6fhrDrC0/eiUlFMAaWiegkojTiWBRmeEj9O9MSmLXFMXQGiY3YC6ukj4QS3
      iKuXgPXH7S9lj8kTF2lNaoqcDw4TGU0i/cQv0BEqsSTKoxNuQhev0sqz8jv87
      8SYtCTI1/1gheYjFhdV0aGdsn6JuJirNWmr5Ebb15IpMXKMvq6H491qMJFYCJ
      C0cq1ad+T3gAsxRdvIgWrU86QMLNxlgyNW+eijTZH5XDvYtVjBovyuf2zZ2P4
      7F+UQNsSLGGLVORcsmBG7ByCMYljVk8i14rWonrXVjPP1fuwIp2AIZzNK6KrJ
      tQzLeb5gEy3A=
  - BOTO_CONFIG=/bogus/value # see: https://github.com/boto/boto/issues/3263
  - ES_VERSION=6.6.2
  - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - ES_JAVA_OPTS="-Xms2g -Xmx2g"
  - ES_HOME="$TRAVIS_BUILD_DIR/elasticsearch-${ES_VERSION}"
  - PATH="$ES_HOME/bin:/usr/lib/postgresql/11/bin:$PATH"

before_install:
- |
  if test ! -f "$ES_HOME/bin/elasticsearch"; then
    wget -q ${ES_DOWNLOAD_URL}
    tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  fi
- java --version
- postgres --version
- elasticsearch --version
- initdb --version
- nvm install 10
- node --version
- npm config set python /usr/bin/python2.7
- pip install -U zc.buildout setuptools redis
- gem install compass

install:
- buildout bootstrap
- bin/buildout -c buildout-travis.cfg || (echo "Retrying buildout" && bin/buildout -c buildout-travis.cfg)

matrix:
  include:
  - python: '3.7'
    addons:
      apt:
        packages:
        - bsdtar
        - graphviz
        - redis-server
        - postgresql-11
        - postgresql-client-11
        - postgresql-server-dev-11
    script:
    - npm test
    - bin/test -v -v --timeout=400 -m "not bdd"
  - python: '3.7'
    env: BROWSER=Chrome
    addons:
      sauce_connect: true
      apt:
        packages:
        - bsdtar
        - graphviz
        - redis-server
        - postgresql-11
        - postgresql-client-11
        - postgresql-server-dev-11
    script:
    - |
      bin/test -v -v --timeout=400 -m "bdd" --tb=short \
        --splinter-implicit-wait 20 \
        --splinter-webdriver remote \
        --splinter-remote-url "https://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com/wd/hub" \
        --splinter-socket-timeout 300 \
        --browser-arg tunnel-identifier "$TRAVIS_JOB_NUMBER" \
        --browser-arg-int build  "$TRAVIS_BUILD_NUMBER" \
        --browser-arg-int idleTimeout 300 \
        --browser-arg name "$TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_COMMIT" \
        --browser-arg browser "$BROWSER" \
        --browser-arg platform "Linux"
